"""initial schema

Revision ID: 17d40d0fabf1
Revises: 
Create Date: 2026-09-20 21:18:17.471512
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '17d40d0fabf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('categories',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('forecast_scenarios',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_scenarios_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('settlements',
    sa.Column('person_name', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_person_name'), ['person_name'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('budgets',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('rollover_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_period_start'), ['period_start'], unique=False)

    op.create_table('loans',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=True),
    sa.Column('debt_type', sa.String(length=20), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate_annual', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('months_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('recurring_rules',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_run_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_post', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rules_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('settlement_payments',
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_payments_settlement_id'), ['settlement_id'], unique=False)

    op.create_table('loan_payments',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.String(length=10), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('paid_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_payments_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_payments_paid_on'), ['paid_on'], unique=False)

    op.create_table('transactions',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recurring_rule_id', sa.Uuid(), nullable=True),
    sa.Column('loan_payment_id', sa.Uuid(), nullable=True),
    sa.Column('settlement_payment_id', sa.Uuid(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_payment_id'], ['loan_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_payment_id'], ['settlement_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_scope'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_payments_paid_on'))
        batch_op.drop_index(batch_op.f('ix_loan_payments_loan_id'))

    op.drop_table('loan_payments')
    with op.batch_alter_table('settlement_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_payments_settlement_id'))

    op.drop_table('settlement_payments')
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rules_deleted_at'))

    op.drop_table('recurring_rules')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_deleted_at'))

    op.drop_table('loans')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_period_start'))
        batch_op.drop_index(batch_op.f('ix_budgets_period_end'))
        batch_op.drop_index(batch_op.f('ix_budgets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_person_name'))
        batch_op.drop_index(batch_op.f('ix_settlements_deleted_at'))

    op.drop_table('settlements')
    with op.batch_alter_table('forecast_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_scenarios_deleted_at'))

    op.drop_table('forecast_scenarios')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_deleted_at'))

    op.drop_table('categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
